

name: GitHub Actions Demo
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: lint code
        run: yarn run lint:fix