name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: macos-latest
    strategy:
      matrix: 
        node-version: [ 19.x ]
    steps:

    -name: yarn install
    run: yarn

    - name: lint fix
    run: yarn run lint:fix
    